//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.08 at 04:04:19 PM WEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://fazaki.com/spring-boot-soap-example-fazaki", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.fazaki.spring_boot_soap_example_fazaki;
